# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Bhumi Designs
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://www.bhumidesigns.com" # the base hostname & protocol for your site, e.g. http://example.com
facebook_username: BhumiDesigns
instagram_username: bhumigardendesigns
email: anjuneil@hotmail.com
phone: 123-456-7890

# Links for the navbar
navigation:
- text: Home
  url: /
- text: About
  url: about
- text: Portfolio
  url: portfolio
- text: Testimonials
  url: testimonials
- text: Blog
  url: blog
- text: Contact
  url: contact

# List of fields for the contact form
contact_form:
- text: Name
  type: text
  name: name
  required: true
- text: Email
  type: email
  name: email
  required: true
- text: Address
  type: text
  name: address
  required: false
- text: Message
  type: textarea
  name: message
  required: true
  isTextArea: true

# Build settings
markdown: kramdown
theme:
gems:
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
